### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by smac89** [brunonova/drmips#2]
First I just want to say THANK YOU for this tool, it is looking very promising and will probably replace MARS once I can figure out why I am getting this error message.

![pig asm -home-casablanca-dropbox-university-cmpt 215-assignments-assignment 4-pig asm - drmips_002](https://cloud.githubusercontent.com/assets/8305511/16604068/cefccd6c-42de-11e6-8371-c232264c1516.png)

I believe the syntax is correct, but not sure why it is showing all those errors.

I guess I should also mention, I am running Ubuntu 16.04 and I installed this via the software center. Currently on version 2.0.1

**Comment by brunonova** [comment]
Hi! Thank you for trying the simulator!
No, DrMIPS is not going to replace MARS. :smile: 

Almost all of those errors are because those instructions aren't supported by the simulator.

The simulator supports a very limited number of instructions. You can see which instructions are supported by clicking on the "i" button in the toolbar or on *Help > Supported instructions* (I think that's the name).

The simulator displays the datapath of the processor graphically, but the datapath is simplified and far from complete: The only instructions that can be used are the ones that the datapath supports.
The simulator includes several datapaths, all based on a Computer Architecture book.

To support all instructions, a complete datapath would be needed, which would be enormous.
Furthermore, syscalls are provided by an operative system, which is not part of the datapath.
The simulator is geared towards education, so the datapath needs to be relatively simple.

For assembly programming, I would recommend using MARS, QtSPIM or something similar ([EduMIPS64](http://www.edumips.org/) is another option for simulating a 64 bit processor).
DrMIPS is best used to see how the unicycle or pipelined datapath works.
